export const DefaultCurrencyRates = {
  "disclaimer": "Usage subject to terms: https://openexchangerates.org/terms",
  "license": "https://openexchangerates.org/license",
  "timestamp": 1552028400,
  "base": "USD",
  "rates": {
    "AED": 3.673181,
    "AFN": 74.998542,
    "ALL": 110.593593,
    "AMD": 488.463133,
    "ANG": 1.814845,
    "AOA": 314.62,
    "ARS": 42.434,
    "AUD": 1.426729,
    "AWG": 1.799996,
    "AZN": 1.7025,
    "BAM": 1.729346,
    "BBD": 2,
    "BDT": 84.118294,
    "BGN": 1.74451,
    "BHD": 0.377027,
    "BIF": 1823.307186,
    "BMD": 1,
    "BND": 1.350711,
    "BOB": 6.907071,
    "BRL": 3.871,
    "BSD": 1,
    "BTC": 0.000256343684,
    "BTN": 70.637746,
    "BWP": 10.68161,
    "BYN": 2.137234,
    "BZD": 2.015578,
    "CAD": 1.345432,
    "CDF": 1637.936317,
    "CHF": 1.009347,
    "CLF": 0.024214,
    "CLP": 667.80202,
    "CNH": 6.731141,
    "CNY": 6.720415,
    "COP": 3133.811122,
    "CRC": 606.355154,
    "CUC": 1,
    "CUP": 25.75,
    "CVE": 98.0015,
    "CZK": 22.860583,
    "DJF": 178,
    "DKK": 6.656108,
    "DOP": 50.595706,
    "DZD": 119.18,
    "EGP": 17.424,
    "ERN": 14.997545,
    "ETB": 28.567276,
    "EUR": 0.892266,
    "FJD": 2.138203,
    "FKP": 0.763739,
    "GBP": 0.763739,
    "GEL": 2.685,
    "GGP": 0.763739,
    "GHS": 5.579618,
    "GIP": 0.763739,
    "GMD": 49.5325,
    "GNF": 9165.126778,
    "GTQ": 7.712013,
    "GYD": 209.186443,
    "HKD": 7.84991,
    "HNL": 24.515455,
    "HRK": 6.615363,
    "HTG": 82.576548,
    "HUF": 282.218999,
    "IDR": 14325.314005,
    "ILS": 3.6283,
    "IMP": 0.763739,
    "INR": 70.02453,
    "IQD": 1205.785426,
    "IRR": 42105,
    "ISK": 121.700198,
    "JEP": 0.763739,
    "JMD": 127.164135,
    "JOD": 0.709302,
    "JPY": 111.08388889,
    "KES": 99.7,
    "KGS": 68.686155,
    "KHR": 4052.130714,
    "KMF": 435.000245,
    "KPW": 900,
    "KRW": 1136.190216,
    "KWD": 0.30407,
    "KYD": 0.833289,
    "KZT": 378.650796,
    "LAK": 8675.084255,
    "LBP": 1511.711574,
    "LKR": 180.526014,
    "LRD": 161.899369,
    "LSL": 14.24,
    "LYD": 1.391935,
    "MAD": 9.649707,
    "MDL": 17.044583,
    "MGA": 3555.859912,
    "MKD": 54.7545,
    "MMK": 1517.934406,
    "MNT": 2453.75,
    "MOP": 8.084899,
    "MRO": 357,
    "MRU": 36.55,
    "MUR": 34.79993,
    "MVR": 15.449981,
    "MWK": 728.572432,
    "MXN": 19.577153,
    "MYR": 4.088476,
    "MZN": 62.76,
    "NAD": 14.24,
    "NGN": 360,
    "NIO": 32.850788,
    "NOK": 8.783732,
    "NPR": 113.01898,
    "NZD": 1.478517,
    "OMR": 0.385,
    "PAB": 1,
    "PEN": 3.309025,
    "PGK": 3.373745,
    "PHP": 52.3,
    "PKR": 139.673758,
    "PLN": 3.849325,
    "PYG": 6090.499786,
    "QAR": 3.641194,
    "RON": 4.231907,
    "RSD": 105.375456,
    "RUB": 66.357,
    "RWF": 894.191978,
    "SAR": 3.75025,
    "SBD": 8.140964,
    "SCR": 13.680381,
    "SDG": 47.612675,
    "SEK": 9.463374,
    "SGD": 1.35949,
    "SHP": 0.763739,
    "SLL": 8390,
    "SOS": 584.565404,
    "SRD": 7.458,
    "SSP": 130.2634,
    "STD": 21050.59961,
    "STN": 21.675,
    "SVC": 8.749193,
    "SYP": 515.000082,
    "SZL": 14.292152,
    "THB": 31.8205,
    "TJS": 9.436222,
    "TMT": 3.50998,
    "TND": 3.054679,
    "TOP": 2.26997,
    "TRY": 5.466886,
    "TTD": 6.789582,
    "TWD": 30.905596,
    "TZS": 2364.3,
    "UAH": 26.637453,
    "UGX": 3701.741337,
    "USD": 1,
    "UYU": 32.703325,
    "UZS": 8390.401976,
    "VEF": 248487.642241,
    "VES": 3294.899604,
    "VND": 23407.115448,
    "VUV": 111.482288,
    "WST": 2.608518,
    "XAF": 585.2881,
    "XAG": 0.06621936,
    "XAU": 0.00077375,
    "XCD": 2.70255,
    "XDR": 0.717706,
    "XOF": 585.2881,
    "XPD": 0.00065715,
    "XPF": 106.475651,
    "XPT": 0.00122505,
    "YER": 250.300587,
    "ZAR": 14.522274,
    "ZMW": 12.024565,
    "ZWL": 322.355011
  }
}

export const CurrencyDict = {
  "ALL": { "currencyName": "Albanian Lek", "currencySymbol": "Lek", "id": "ALL" },
  "XCD": { "currencyName": "East Caribbean Dollar", "currencySymbol": "$", "id": "XCD" },
  "EUR": { "currencyName": "Euro", "currencySymbol": "€", "id": "EUR" },
  "BBD": { "currencyName": "Barbadian Dollar", "currencySymbol": "$", "id": "BBD" },
  "BTN": { "currencyName": "Bhutanese Ngultrum", "id": "BTN" },
  "BND": { "currencyName": "Brunei Dollar", "currencySymbol": "$", "id": "BND" },
  "XAF": { "currencyName": "Central African CFA Franc", "id": "XAF" },
  "CUP": { "currencyName": "Cuban Peso", "currencySymbol": "$", "id": "CUP" },
  "USD": { "currencyName": "United States Dollar", "currencySymbol": "$", "id": "USD" },
  "FKP": { "currencyName": "Falkland Islands Pound", "currencySymbol": "£", "id": "FKP" },
  "GIP": { "currencyName": "Gibraltar Pound", "currencySymbol": "£", "id": "GIP" },
  "HUF": { "currencyName": "Hungarian Forint", "currencySymbol": "Ft", "id": "HUF" },
  "IRR": { "currencyName": "Iranian Rial", "currencySymbol": "﷼", "id": "IRR" },
  "JMD": { "currencyName": "Jamaican Dollar", "currencySymbol": "J$", "id": "JMD" },
  "AUD": { "currencyName": "Australian Dollar", "currencySymbol": "$", "id": "AUD" },
  "LAK": { "currencyName": "Lao Kip", "currencySymbol": "₭", "id": "LAK" },
  "LYD": { "currencyName": "Libyan Dinar", "id": "LYD" },
  "MKD": { "currencyName": "Macedonian Denar", "currencySymbol": "ден", "id": "MKD" },
  "XOF": { "currencyName": "West African CFA Franc", "id": "XOF" },
  "NZD": { "currencyName": "New Zealand Dollar", "currencySymbol": "$", "id": "NZD" },
  "OMR": { "currencyName": "Omani Rial", "currencySymbol": "﷼", "id": "OMR" },
  "PGK": { "currencyName": "Papua New Guinean Kina", "id": "PGK" },
  "RWF": { "currencyName": "Rwandan Franc", "id": "RWF" },
  "WST": { "currencyName": "Samoan Tala", "id": "WST" },
  "RSD": { "currencyName": "Serbian Dinar", "currencySymbol": "Дин.", "id": "RSD" },
  "SEK": { "currencyName": "Swedish Krona", "currencySymbol": "kr", "id": "SEK" },
  "TZS": { "currencyName": "Tanzanian Shilling", "currencySymbol": "TSh", "id": "TZS" },
  "AMD": { "currencyName": "Armenian Dram", "id": "AMD" },
  "BSD": { "currencyName": "Bahamian Dollar", "currencySymbol": "$", "id": "BSD" },
  "BAM": { "currencyName": "Bosnia And Herzegovina Konvertibilna Marka", "currencySymbol": "KM", "id": "BAM" },
  "CVE": { "currencyName": "Cape Verdean Escudo", "id": "CVE" },
  "CNY": { "currencyName": "Chinese Yuan", "currencySymbol": "¥", "id": "CNY" },
  "CRC": { "currencyName": "Costa Rican Colon", "currencySymbol": "₡", "id": "CRC" },
  "CZK": { "currencyName": "Czech Koruna", "currencySymbol": "Kč", "id": "CZK" },
  "ERN": { "currencyName": "Eritrean Nakfa", "id": "ERN" },
  "GEL": { "currencyName": "Georgian Lari", "id": "GEL" },
  "HTG": { "currencyName": "Haitian Gourde", "id": "HTG" },
  "INR": { "currencyName": "Indian Rupee", "currencySymbol": "₹", "id": "INR" },
  "JOD": { "currencyName": "Jordanian Dinar", "id": "JOD" },
  "KRW": { "currencyName": "South Korean Won", "currencySymbol": "₩", "id": "KRW" },
  "LBP": { "currencyName": "Lebanese Lira", "currencySymbol": "£", "id": "LBP" },
  "MWK": { "currencyName": "Malawian Kwacha", "id": "MWK" },
  "MRO": { "currencyName": "Mauritanian Ouguiya", "id": "MRO" },
  "MZN": { "currencyName": "Mozambican Metical", "id": "MZN" },
  "ANG": { "currencyName": "Netherlands Antillean Gulden", "currencySymbol": "ƒ", "id": "ANG" },
  "PEN": { "currencyName": "Peruvian Nuevo Sol", "currencySymbol": "S/.", "id": "PEN" },
  "QAR": { "currencyName": "Qatari Riyal", "currencySymbol": "﷼", "id": "QAR" },
  "STD": { "currencyName": "Sao Tome And Principe Dobra", "id": "STD" },
  "SLL": { "currencyName": "Sierra Leonean Leone", "id": "SLL" },
  "SOS": { "currencyName": "Somali Shilling", "currencySymbol": "S", "id": "SOS" },
  "SDG": { "currencyName": "Sudanese Pound", "id": "SDG" },
  "SYP": { "currencyName": "Syrian Pound", "currencySymbol": "£", "id": "SYP" },
  "AOA": { "currencyName": "Angolan Kwanza", "id": "AOA" },
  "AWG": { "currencyName": "Aruban Florin", "currencySymbol": "ƒ", "id": "AWG" },
  "BHD": { "currencyName": "Bahraini Dinar", "id": "BHD" },
  "BZD": { "currencyName": "Belize Dollar", "currencySymbol": "BZ$", "id": "BZD" },
  "BWP": { "currencyName": "Botswana Pula", "currencySymbol": "P", "id": "BWP" },
  "BIF": { "currencyName": "Burundi Franc", "id": "BIF" },
  "KYD": { "currencyName": "Cayman Islands Dollar", "currencySymbol": "$", "id": "KYD" },
  "COP": { "currencyName": "Colombian Peso", "currencySymbol": "$", "id": "COP" },
  "DKK": { "currencyName": "Danish Krone", "currencySymbol": "kr", "id": "DKK" },
  "GTQ": { "currencyName": "Guatemalan Quetzal", "currencySymbol": "Q", "id": "GTQ" },
  "HNL": { "currencyName": "Honduran Lempira", "currencySymbol": "L", "id": "HNL" },
  "IDR": { "currencyName": "Indonesian Rupiah", "currencySymbol": "Rp", "id": "IDR" },
  "ILS": { "currencyName": "Israeli New Sheqel", "currencySymbol": "₪", "id": "ILS" },
  "KZT": { "currencyName": "Kazakhstani Tenge", "currencySymbol": "лв", "id": "KZT" },
  "KWD": { "currencyName": "Kuwaiti Dinar", "id": "KWD" },
  "LSL": { "currencyName": "Lesotho Loti", "id": "LSL" },
  "MYR": { "currencyName": "Malaysian Ringgit", "currencySymbol": "RM", "id": "MYR" },
  "MUR": { "currencyName": "Mauritian Rupee", "currencySymbol": "₨", "id": "MUR" },
  "MNT": { "currencyName": "Mongolian Tugrik", "currencySymbol": "₮", "id": "MNT" },
  "MMK": { "currencyName": "Myanma Kyat", "id": "MMK" },
  "NGN": { "currencyName": "Nigerian Naira", "currencySymbol": "₦", "id": "NGN" },
  "PAB": { "currencyName": "Panamanian Balboa", "currencySymbol": "B/.", "id": "PAB" },
  "PHP": { "currencyName": "Philippine Peso", "currencySymbol": "₱", "id": "PHP" },
  "RON": { "currencyName": "Romanian Leu", "currencySymbol": "lei", "id": "RON" },
  "SAR": { "currencyName": "Saudi Riyal", "currencySymbol": "﷼", "id": "SAR" },
  "SGD": { "currencyName": "Singapore Dollar", "currencySymbol": "$", "id": "SGD" },
  "ZAR": { "currencyName": "South African Rand", "currencySymbol": "R", "id": "ZAR" },
  "SRD": { "currencyName": "Surinamese Dollar", "currencySymbol": "$", "id": "SRD" },
  "TWD": { "currencyName": "New Taiwan Dollar", "currencySymbol": "NT$", "id": "TWD" },
  "TOP": { "currencyName": "Paanga", "id": "TOP" },
  "VEF": { "currencyName": "Venezuelan Bolivar", "id": "VEF" },
  "DZD": { "currencyName": "Algerian Dinar", "id": "DZD" },
  "ARS": { "currencyName": "Argentine Peso", "currencySymbol": "$", "id": "ARS" },
  "AZN": { "currencyName": "Azerbaijani Manat", "currencySymbol": "ман", "id": "AZN" },
  "BYR": { "currencyName": "Belarusian Ruble", "currencySymbol": "p.", "id": "BYR" },
  "BOB": { "currencyName": "Bolivian Boliviano", "currencySymbol": "$b", "id": "BOB" },
  "BGN": { "currencyName": "Bulgarian Lev", "currencySymbol": "лв", "id": "BGN" },
  "CAD": { "currencyName": "Canadian Dollar", "currencySymbol": "$", "id": "CAD" },
  "CLP": { "currencyName": "Chilean Peso", "currencySymbol": "$", "id": "CLP" },
  "CDF": { "currencyName": "Congolese Franc", "id": "CDF" },
  "DOP": { "currencyName": "Dominican Peso", "currencySymbol": "RD$", "id": "DOP" },
  "FJD": { "currencyName": "Fijian Dollar", "currencySymbol": "$", "id": "FJD" },
  "GMD": { "currencyName": "Gambian Dalasi", "id": "GMD" },
  "GYD": { "currencyName": "Guyanese Dollar", "currencySymbol": "$", "id": "GYD" },
  "ISK": { "currencyName": "Icelandic Króna", "currencySymbol": "kr", "id": "ISK" },
  "IQD": { "currencyName": "Iraqi Dinar", "id": "IQD" },
  "JPY": { "currencyName": "Japanese Yen", "currencySymbol": "¥", "id": "JPY" },
  "KPW": { "currencyName": "North Korean Won", "currencySymbol": "₩", "id": "KPW" },
  "LVL": { "currencyName": "Latvian Lats", "currencySymbol": "Ls", "id": "LVL" },
  "CHF": { "currencyName": "Swiss Franc", "currencySymbol": "Fr.", "id": "CHF" },
  "MGA": { "currencyName": "Malagasy Ariary", "id": "MGA" },
  "MDL": { "currencyName": "Moldovan Leu", "id": "MDL" },
  "MAD": { "currencyName": "Moroccan Dirham", "id": "MAD" },
  "NPR": { "currencyName": "Nepalese Rupee", "currencySymbol": "₨", "id": "NPR" },
  "NIO": { "currencyName": "Nicaraguan Cordoba", "currencySymbol": "C$", "id": "NIO" },
  "PKR": { "currencyName": "Pakistani Rupee", "currencySymbol": "₨", "id": "PKR" },
  "PYG": { "currencyName": "Paraguayan Guarani", "currencySymbol": "Gs", "id": "PYG" },
  "SHP": { "currencyName": "Saint Helena Pound", "currencySymbol": "£", "id": "SHP" },
  "SCR": { "currencyName": "Seychellois Rupee", "currencySymbol": "₨", "id": "SCR" },
  "SBD": { "currencyName": "Solomon Islands Dollar", "currencySymbol": "$", "id": "SBD" },
  "LKR": { "currencyName": "Sri Lankan Rupee", "currencySymbol": "₨", "id": "LKR" },
  "THB": { "currencyName": "Thai Baht", "currencySymbol": "฿", "id": "THB" },
  "TRY": { "currencyName": "Turkish New Lira", "id": "TRY" },
  "AED": { "currencyName": "UAE Dirham", "id": "AED" },
  "VUV": { "currencyName": "Vanuatu Vatu", "id": "VUV" },
  "YER": { "currencyName": "Yemeni Rial", "currencySymbol": "﷼", "id": "YER" },
  "AFN": { "currencyName": "Afghan Afghani", "currencySymbol": "؋", "id": "AFN" },
  "BDT": { "currencyName": "Bangladeshi Taka", "id": "BDT" },
  "BRL": { "currencyName": "Brazilian Real", "currencySymbol": "R$", "id": "BRL" },
  "KHR": { "currencyName": "Cambodian Riel", "currencySymbol": "៛", "id": "KHR" },
  "KMF": { "currencyName": "Comorian Franc", "id": "KMF" },
  "HRK": { "currencyName": "Croatian Kuna", "currencySymbol": "kn", "id": "HRK" },
  "DJF": { "currencyName": "Djiboutian Franc", "id": "DJF" },
  "EGP": { "currencyName": "Egyptian Pound", "currencySymbol": "£", "id": "EGP" },
  "ETB": { "currencyName": "Ethiopian Birr", "id": "ETB" },
  "XPF": { "currencyName": "CFP Franc", "id": "XPF" },
  "GHS": { "currencyName": "Ghanaian Cedi", "id": "GHS" },
  "GNF": { "currencyName": "Guinean Franc", "id": "GNF" },
  "HKD": { "currencyName": "Hong Kong Dollar", "currencySymbol": "$", "id": "HKD" },
  "XDR": { "currencyName": "Special Drawing Rights", "id": "XDR" },
  "KES": { "currencyName": "Kenyan Shilling", "currencySymbol": "KSh", "id": "KES" },
  "KGS": { "currencyName": "Kyrgyzstani Som", "currencySymbol": "лв", "id": "KGS" },
  "LRD": { "currencyName": "Liberian Dollar", "currencySymbol": "$", "id": "LRD" },
  "MOP": { "currencyName": "Macanese Pataca", "id": "MOP" },
  "MVR": { "currencyName": "Maldivian Rufiyaa", "id": "MVR" },
  "MXN": { "currencyName": "Mexican Peso", "currencySymbol": "$", "id": "MXN" },
  "NAD": { "currencyName": "Namibian Dollar", "currencySymbol": "$", "id": "NAD" },
  "NOK": { "currencyName": "Norwegian Krone", "currencySymbol": "kr", "id": "NOK" },
  "PLN": { "currencyName": "Polish Zloty", "currencySymbol": "zł", "id": "PLN" },
  "RUB": { "currencyName": "Russian Ruble", "currencySymbol": "руб", "id": "RUB" },
  "SZL": { "currencyName": "Swazi Lilangeni", "id": "SZL" },
  "TJS": { "currencyName": "Tajikistani Somoni", "id": "TJS" },
  "TTD": { "currencyName": "Trinidad and Tobago Dollar", "currencySymbol": "TT$", "id": "TTD" },
  "UGX": { "currencyName": "Ugandan Shilling", "currencySymbol": "USh", "id": "UGX" },
  "UYU": { "currencyName": "Uruguayan Peso", "currencySymbol": "$U", "id": "UYU" },
  "VND": { "currencyName": "Vietnamese Dong", "currencySymbol": "₫", "id": "VND" },
  "TND": { "currencyName": "Tunisian Dinar", "id": "TND" },
  "UAH": { "currencyName": "Ukrainian Hryvnia", "currencySymbol": "₴", "id": "UAH" },
  "UZS": { "currencyName": "Uzbekistani Som", "currencySymbol": "лв", "id": "UZS" },
  "TMT": { "currencyName": "Turkmenistan Manat", "id": "TMT" },
  "GBP": { "currencyName": "British Pound", "currencySymbol": "£", "id": "GBP" },
  "ZMW": { "currencyName": "Zambian Kwacha", "id": "ZMW" },
  "BTC": { "currencyName": "Bitcoin", "currencySymbol": "BTC", "id": "BTC" },
  "BYN": { "currencyName": "New Belarusian Ruble", "currencySymbol": "p.", "id": "BYN" }
}

export const CurrencyDict_temp = {
  "EUR": { "currencyName": "Euro", "currencySymbol": "€", "id": "EUR" },
  "CNY": { "currencyName": "Chinese Yuan", "currencySymbol": "¥", "id": "CNY" },
  "USD": { "currencyName": "United States Dollar", "currencySymbol": "$", "id": "USD" },
  "HKD": { "currencyName": "Hong Kong Dollar", "currencySymbol": "$", "id": "HKD" },
  "JPY": { "currencyName": "Japanese Yen", "currencySymbol": "¥", "id": "JPY" },
  "GBP": { "currencyName": "British Pound", "currencySymbol": "£", "id": "GBP" }
}

export const AllCurrencyNames = Object.keys(CurrencyDict).sort()

export const DefaultShowCurrency = ["USD", "HKD", "CNY"]
